// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: user.sql

package db

import (
	"context"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (
  username, hashed_passwd, full_name, email_id
) VALUES (
  $1, $2, $3, $4
) RETURNING username, full_name, hashed_passwd, email_id, passwd_updated_at, created_at
`

type CreateUserParams struct {
	Username     string `json:"username"`
	HashedPasswd string `json:"hashed_passwd"`
	FullName     string `json:"full_name"`
	EmailID      string `json:"email_id"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser,
		arg.Username,
		arg.HashedPasswd,
		arg.FullName,
		arg.EmailID,
	)
	var i User
	err := row.Scan(
		&i.Username,
		&i.FullName,
		&i.HashedPasswd,
		&i.EmailID,
		&i.PasswdUpdatedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getUser = `-- name: GetUser :one
SELECT username, full_name, hashed_passwd, email_id, passwd_updated_at, created_at FROM users
WHERE username = $1 LIMIT 1
`

func (q *Queries) GetUser(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUser, username)
	var i User
	err := row.Scan(
		&i.Username,
		&i.FullName,
		&i.HashedPasswd,
		&i.EmailID,
		&i.PasswdUpdatedAt,
		&i.CreatedAt,
	)
	return i, err
}
